apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjenkins-deploy
  labels:
    app: myjenkins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myjenkins
  template:
    metadata:
      labels:
        app: myjenkins
    spec:
      containers:
      - name: myjenkins-container
        image: maha4iac/myonlinebooking:2
        ports:
        - containerPort: 8080