apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector: 
     app: myjekins-pod
     version: 2.7.1
   template:
     metadata:
       labels:
          app: myjekins-pod
          version: 2.7.1
     spec:
        containers:
        - name: myjenkins-container   
          image: maha4iac/myjenkins
          ports:
          - containerPort: 8080  